// Command report bundles a benchmark run into one self-contained HTML page.
//
// Static, not live: it reads what `just bench` and `just compare` already
// wrote and inlines it. There is no server, no JavaScript fetching anything,
// and no external asset — the file can be opened from disk, emailed, or served
// later by the Go binary without modification.
//
// This is the metrics panel in its static form. The live dashboard reuses the
// same figures and the same numbers; it only changes where they come from.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"html/template"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/yug/upi-city/internal/explain"
	"github.com/yug/upi-city/internal/metrics"
	"github.com/yug/upi-city/internal/risk"
)

type comparisonRow struct {
	Name      string                `json:"name"`
	Detectors []string              `json:"detectors"`
	AUCPR     float64               `json:"aucpr_mean"`
	AUCPRMin  float64               `json:"aucpr_min"`
	AUCPRMax  float64               `json:"aucpr_max"`
	Precision float64               `json:"precision_mean"`
	Recall    float64               `json:"recall_mean"`
	FPPer1k   float64               `json:"fp_per_1k_legit_mean"`
	LatencyS  float64               `json:"latency_seconds_mean"`
	Missed    int                   `json:"incidents_never_detected"`
	Total     int                   `json:"incidents_total"`
	ECE       float64               `json:"expected_calibration_error,omitempty"`
	Bins      []risk.ReliabilityBin `json:"reliability,omitempty"`
}

type propagationRow struct {
	Name         string  `json:"name"`
	AUCPR        float64 `json:"aucpr_mean"`
	Precision    float64 `json:"precision_mean"`
	Recall       float64 `json:"recall_mean"`
	MerchantFP1k float64 `json:"merchant_fp_per_1k"`
}

type page struct {
	Summary    metrics.Summary
	Seeds      []metrics.Report
	Comparison []comparisonRow
	Figures    []figure
	BestConfig comparisonRow
	Baselines  []namedStat
	// Head is one representative run, used for the sections that describe a
	// policy rather than an aggregate.
	Head         metrics.Report
	Explanations []explain.Explanation
	Propagation  []propagationRow
	Generated    string
}

type figure struct {
	Title string
	Note  string
	SVG   template.HTML
}

type namedStat struct {
	Name string
	Stat metrics.Stat
}

func main() {
	dir := flag.String("dir", "results", "directory holding summary.json and figures/")
	out := flag.String("out", "results/report.html", "output file")
	flag.Parse()

	var p page
	p.Generated = "generated by `just report-html` from committed results"

	if err := readJSON(filepath.Join(*dir, "summary.json"), &p.Summary); err != nil {
		fmt.Fprintln(os.Stderr, "summary.json:", err, "\n(run `just bench` first)")
		os.Exit(1)
	}
	_ = readJSON(filepath.Join(*dir, "comparison.json"), &p.Comparison)

	for i := 1; i <= p.Summary.Seeds; i++ {
		var r metrics.Report
		if err := readJSON(filepath.Join(*dir, fmt.Sprintf("seed-%02d", i), "metrics.json"), &r); err == nil {
			p.Seeds = append(p.Seeds, r)
		}
	}

	for _, c := range p.Comparison {
		if c.AUCPR > p.BestConfig.AUCPR {
			p.BestConfig = c
		}
	}

	names := make([]string, 0, len(p.Summary.BaselineAUCPR))
	for n := range p.Summary.BaselineAUCPR {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		p.Baselines = append(p.Baselines, namedStat{n, p.Summary.BaselineAUCPR[n]})
	}

	figs := []struct{ file, title, note string }{
		{"pr-curve.svg", "Precision vs recall",
			"The three dashed lines are trivial scorers. Without them an AUC-PR of 0.05 is unreadable — it could be excellent or worthless."},
		{"trade-curve.svg", "What each threshold buys, and what it costs",
			"Recall rises with a lower threshold; so does the number of legitimate customers caught up in it. The chosen point is a decision, not a discovery."},
		{"fp-breakdown.svg", "Who absorbs the false positives",
			"Red bars are the hard negatives — legitimate traffic built to be confusable with fraud. Errors concentrating there means the problem is genuinely hard rather than the detector being noisy."},
		{"reliability.svg", "Calibration",
			"Fitted on seeds 1-5, plotted on seeds 6-10 it never saw. Fitting and reporting on the same run produces a flawless-looking diagram regardless of how bad the scores are."},
		{"budget-curve.svg", "What a bigger review queue buys",
			"Reviewer capacity is the scarce resource. The useful question is not how good the model is, but how much fraud N analysts can stop — and where more staff stop buying anything."},
		{"intensity.svg", "Recall vs attack intensity",
			"How loud must an attack be before the detector notices it? Only computable because the attack ramps: with instant-on fraud every transaction sits in the top bucket and the curve does not exist."},
		{"propagation.svg", "Guilt by association — measured, not assumed",
			"Naive propagation flags 93% of a large merchant's legitimate traffic and collapses detection to chance. Degree normalisation fixes the merchant harm entirely, and detection is still worse than not doing it at all. It ships off by default."},
		{"latency-seeds.svg", "Detection latency by seed",
			"One run is an anecdote. Latency here ranges from under two seconds to over twenty depending only on which world was simulated."},
	}
	for _, f := range figs {
		b, err := os.ReadFile(filepath.Join(*dir, "figures", f.file))
		if err != nil {
			continue
		}
		p.Figures = append(p.Figures, figure{Title: f.title, Note: f.note, SVG: template.HTML(b)})
	}

	if len(p.Seeds) > 0 {
		p.Head = p.Seeds[0]
	}

	_ = readJSON(filepath.Join(*dir, "propagation.json"), &p.Propagation)

	var byKey map[string]explain.Explanation
	if readJSON(filepath.Join(*dir, "explanations.json"), &byKey) == nil {
		keys := make([]string, 0, len(byKey))
		for k := range byKey {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			p.Explanations = append(p.Explanations, byKey[k])
		}
	}

	tpl := template.Must(template.New("report").Funcs(template.FuncMap{
		"pct": func(f float64) string { return fmt.Sprintf("%.2f%%", f*100) },
		"f3":  func(f float64) string { return fmt.Sprintf("%.3f", f) },
		"f2":  func(f float64) string { return fmt.Sprintf("%.2f", f) },
		"f1":  func(f float64) string { return fmt.Sprintf("%.1f", f) },
		"f4":  func(f float64) string { return fmt.Sprintf("%.4f", f) },
		"ratio": func(a, b float64) string {
			if b == 0 {
				return "—"
			}
			return fmt.Sprintf("%.0f", a/b)
		},
		"join":   func(s []string) string { return strings.Join(s, " + ") },
		"isBest": func(a, b comparisonRow) bool { return a.Name == b.Name },
	}).Parse(pageTpl))

	f, err := os.Create(*out)
	if err != nil {
		fmt.Fprintln(os.Stderr, "create:", err)
		os.Exit(1)
	}
	defer f.Close()
	if err := tpl.Execute(f, p); err != nil {
		fmt.Fprintln(os.Stderr, "render:", err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s\n", *out)
}

func readJSON(path string, v any) error {
	b, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	return json.Unmarshal(b, v)
}
